trigger:
- main

pool:
  name: Default  # Jeśli chcesz używać agenta w domyślnej puli
  demands:
    - agent.name -equals AgentSelfHosted  # Dodaj nazwę swojego agenta lokalnego, jeśli masz wiele agentów

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Krok 1: Instalacja narzędzi NuGet i przywracanie zależności
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

# Krok 2: Przechodzimy do folderu z projektem .NET (np. "api") i budujemy rozwiązanie .NET
- script: |
    cd api  # Przechodzimy do folderu "api", w którym znajduje się projekt .NET
    dotnet restore  # Przywracamy zależności NuGet dla projektu .NET
    dotnet build -c Release  # Budujemy projekt .NET
  displayName: 'Build .NET API'

# Krok 3: Opcjonalnie uruchamianie testów jednostkowych (jeśli masz testy w projekcie .NET)
- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: 'Run Tests'
