trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals AgentSelfHosted

variables:
  solution: 'api/api.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: |
    dotnet restore $(solution)
    dotnet build $(solution) -c $(buildConfiguration)
  displayName: 'Build .NET API'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: 'Run Tests'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd front
    npm install
    npm run build
  displayName: 'Build React App'

  - script: |
    rm -r api/wwwroot/*
    cp -r frontend/build/* api/wwwroot/
  displayName: 'Copy React Build to API wwwroot'

