trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals AgentSelfHosted

variables:
  solution: 'api/api.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: |
    dotnet restore $(solution)
    dotnet build $(solution) -c $(buildConfiguration)
  displayName: 'Build .NET API'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: 'Run Tests'
